name: Build Hanoip Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update

          sudo apt install -y \
            bc \
            bison \
            build-essential \
            ccache \
            curl \
            flex \
            gcc \
            git \
            libssl-dev \
            lld \
            llvm \
            python3

      - name: Clone Proton Clang
        run: |
          git clone --depth=1 \
          https://github.com/kdrag0n/proton-clang.git \
          clang

      - name: Build Kernel
        run: |

          export ARCH=arm64
          export SUBARCH=arm64

          export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH

          mkdir out

          make O=out vendor/hanoip-perf_defconfig

          scripts/config \
            --file out/.config \
            -e NAMESPACES \
            -e UTS_NS \
            -e IPC_NS \
            -e PID_NS \
            -e NET_NS \
            -e USER_NS \
            -e CGROUPS \
            -e MEMCG \
            -e OVERLAY_FS \
            -e SECCOMP \
            -e VETH \
            -e TUN \
            -e BRIDGE

          make O=out olddefconfig

          make -j$(nproc) \
            O=out \
            CC=clang \
            LLVM=1 \
            LLVM_IAS=1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: |
            out/arch/arm64/boot/Image*
            out/arch/arm64/boot/dtbo.img
